# https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Preview
      url: https://${{github.run_id}}--fari-community.netlify.app
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      # Use Bun
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.15
      # Install
      - name: Install
        run: bun install
      # Build
      - name: Build
        run: bun run build
      # Deploy Preview
      - name: Deploy Preview
        if: github.ref != 'refs/heads/main' && !github.event.pull_request.head.repo.fork
        run: bun run deploy:preview -- --auth ${{secrets.NETLIFY_AUTH_TOKEN}} --alias $GITHUB_RUN_ID
      # Deploy Production
      - name: Deploy Production
        if: github.ref == 'refs/heads/main' && !github.event.pull_request.head.repo.fork
        run: bun run deploy:prod -- --auth ${{secrets.NETLIFY_AUTH_TOKEN}}
