# https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      # Use Bun
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      # Install
      - name: Install
        run: bun install
      # Build
      - name: Build
        run: bun run build
      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: out
          path: out
  deploy-preview:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && !github.event.pull_request.head.repo.fork
    environment:
      name: Preview
      url: https://${{github.run_id}}--fari-community.netlify.app
    steps:
      # Setup
      - uses: actions/checkout@v2
      # Use Bun
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      # Install
      - name: Install
        run: bun install
      # Download Artifacts
      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: out
          path: out
      # Deploy Preview
      - name: Deploy Preview
        run: bun run deploy:preview -- --auth ${{secrets.NETLIFY_AUTH_TOKEN}} --alias $GITHUB_RUN_ID
  deploy-production:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && !github.event.pull_request.head.repo.fork
    environment:
      name: Production
      url: https://fari.community
    steps:
      # Setup
      - uses: actions/checkout@v2
      # Use Bun
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      # Install
      - name: Install
        run: bun install
      # Download Artifacts
      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: out
          path: out
      # Deploy Production
      - name: Deploy Production
        run: bun run deploy:prod -- --auth ${{secrets.NETLIFY_AUTH_TOKEN}}
